baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
	css = 'https://somecdn.css'
	 


[markup]
	[markup.highlight]
		anchorLineNos = false
		codeFences = true
		guessSyntax = false
		hl_Lines = ''
		hl_inline = false
		lineAnchors = ''
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		noHl = false
		tabWidth = 2
		style = 'dracula'
	[markup.goldmark.renderer]
		hardWraps = true

